### ISSUE TITLE
In GitBook 3.2.0 inserts escape characters

### ISSUE THREAD

**Issue by stefwrite** [Erwin-Chan/gitbook-plugin-fbqx#2]
To take advantage of other features, I recently updated to use GitBook 3.2.0. I was using this plugin successfully in 2.6.6, but with 3.2.0 it tries to escape some or all of the "#" symbols. I can't seem to track down what in the newer code is doing this or how to disable it.

Code in my markdown file:
`{%fbq%}Testing. Please type $$hello## (hello) and $$world## (world).{%endfbq%}`

How it renders in my browser, just above the "Submit" button:
`Testing. Please type ______________ (hello) and $$world\#\# \(world\).`

The Submit button and results text appear to work fine, but they automatically go to a "Correct" state without my having entered anything.

I can try to track down what is escaping the "#" characters and see if I can prevent that from happening, but I suspect there is more that needs to be resolved here.

**Comment by stefwrite** [comment]
Update based on my experimenting today: I was able to get the questions to render blanks instead of escaped "#" characters if I changed the index.js in the plugin to use "@@" instead of "##", though it still wanted to escape the parentheses around the last word in the sentence:

The lines I changed in the index.js file; note the "@@" replacing the "##" in each line:
`29>                    ans.push(substr[i].split("@@", 1));`
`30>                    var str = '$$' + ans[i - 1].toString() + '@@';`

In the markdown file:
`{%fbq%}Testing. Please type $$hello@@ (hello) and $$world@@ (world).{%endfbq%}`

In the browser display:
`Testing. Please type ____________ (hello) and _____________  \(world\).`

The behavior of the blanks and the incorrect/correct states started working again by using this workaround. Since this involves a fundamental change in the instructions for plugin use, though, I hesitate to submit it as a patch. I will let the owners decide how they want to address the issue more permanently.

**Comment by isaacyiu0369** [comment]
Thanks for the detailed and helpful comments. Give me some time to look into it, will report back asap.

**Comment by isaacyiu0369** [comment]
It turns out that gitbook 3.0+ will auto escape characters like #, I fixed it by running the content through a markdown parser first before replacing the code. The changes has been published as version 1.0.0.

Thanks for reporting. Please report back if you found any other issues.
