### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by stefwrite** [Erwin-Chan/gitbook-plugin-fbqx#3]
I was excited about the recent fix to accommodate the character escaping in 3.0+. After I installed the update, though, I seem to be running into a new issue. I am working with GitBook 3.2.0.

On the page that I included one _fbqx_ plugin call, both _gitbook build_ and _gitbook serve_ resulted in the following, which terminated the process immediately:

```
error: error while generating page "sect-ourmarkdown/ourmarkdown-fbqx.md": 

Template render error: (/(redacted)/stef-sandbox/sect-ourmarkdown/ourmarkdown-fbqx.md)
  ReferenceError: Promise is not defined
```

I see _Promise_ called as a new object in index.js for the plugin, but perhaps I am missing something that allows it to render? Here is the code from the page

`{%fbq%}Use the $$cd## command to change directories.{%endfbq%}`

If I remove that plugin call from my book, it builds without any issues. I can provide more info if needed.

**Comment by stefwrite** [comment]
I re-ran my build with --debug for more details:

```
error: error while generating page "sect-ourmarkdown/ourmarkdown-fbqx.md": 

Template render error: (/home/stef/dev/support_training/stef-sandbox/sect-ourmarkdown/ourmarkdown-fbqx.md)
  ReferenceError: Promise is not defined
Template render error: (/home/stef/dev/support_training/stef-sandbox/sect-ourmarkdown/ourmarkdown-fbqx.md)
  ReferenceError: Promise is not defined
    at Object.exports.prettifyError (/home/stef/.gitbook/versions/3.2.0/node_modules/nunjucks/src/lib.js:34:15)
    at /home/stef/.gitbook/versions/3.2.0/node_modules/nunjucks/src/environment.js:485:31
    at eval (eval at <anonymous> (/home/stef/.gitbook/versions/3.2.0/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:18:11)
    at /home/stef/.gitbook/versions/3.2.0/node_modules/q/q.js:2031:17
    at runSingle (/home/stef/.gitbook/versions/3.2.0/node_modules/q/q.js:137:13)
    at flush (/home/stef/.gitbook/versions/3.2.0/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:442:13)

```

**Comment by isaacyiu0369** [comment]
May I ask what version of node do you happen to be using?

**Comment by stefwrite** [comment]
Running _node --version_ returns _v0.10.36_, and it's the latest in the Fedora repos I get it from. Should I back that up to an earlier version or install a newer one?

Also let me know any other command outputs I can provide for you. Thanks for looking into it.

**Comment by isaacyiu0369** [comment]
definitely a newer one, promise is supported only for node 0.11+
Install at least node 4.0+, you can find instruction for installing it on fedora [here](https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora)

**Comment by stefwrite** [comment]
Thanks... I'm currently on F21, and yum locally was telling me it was the latest version, but I will see if I can investigate further.

```
Package nodejs-0.10.36-3.fc21.x86_64 already installed and latest version
Package npm-1.3.6-6.fc21.noarch already installed and latest version
```

**Comment by stefwrite** [comment]
One of my associates running F24 has the right version, so I am working with him to get my own system updated. I will let you know if I run into any issues once I get the latest nodejs running. Otherwise, thanks for taking time to ask. Really loving the plugin. :-)

**Comment by stefwrite** [comment]
One final note: got updated to nodejs 4.x by just installing the RPM directly for F21, and the plugin is working great. Thanks again!

**Comment by isaacyiu0369** [comment]
Great to hear!
